//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 03:45:49 PM CST 
//


package com.ecms.customs.vo.cust1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ecms.customs.vo.cust1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ecms.customs.vo.cust1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CBEC }
     * 
     */
    public CBEC createCBEC() {
        return new CBEC();
    }

    /**
     * Create an instance of {@link DeclarantType }
     * 
     */
    public DeclarantType createDeclarantType() {
        return new DeclarantType();
    }

    /**
     * Create an instance of {@link DeclarantType.Person }
     * 
     */
    public DeclarantType.Person createDeclarantTypePerson() {
        return new DeclarantType.Person();
    }

    /**
     * Create an instance of {@link CBEC.Declaration }
     * 
     */
    public CBEC.Declaration createCBECDeclaration() {
        return new CBEC.Declaration();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order }
     * 
     */
    public CBEC.Declaration.Order createCBECDeclarationOrder() {
        return new CBEC.Declaration.Order();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.Payment }
     * 
     */
    public CBEC.Declaration.Order.Payment createCBECDeclarationOrderPayment() {
        return new CBEC.Declaration.Order.Payment();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.OtherPayment }
     * 
     */
    public CBEC.Declaration.Order.OtherPayment createCBECDeclarationOrderOtherPayment() {
        return new CBEC.Declaration.Order.OtherPayment();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.Buyer }
     * 
     */
    public CBEC.Declaration.Order.Buyer createCBECDeclarationOrderBuyer() {
        return new CBEC.Declaration.Order.Buyer();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link DeclarantType.Company }
     * 
     */
    public DeclarantType.Company createDeclarantTypeCompany() {
        return new DeclarantType.Company();
    }

    /**
     * Create an instance of {@link DeclarantType.Person.IDNumber }
     * 
     */
    public DeclarantType.Person.IDNumber createDeclarantTypePersonIDNumber() {
        return new DeclarantType.Person.IDNumber();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.ECommercePlatForm }
     * 
     */
    public CBEC.Declaration.Order.ECommercePlatForm createCBECDeclarationOrderECommercePlatForm() {
        return new CBEC.Declaration.Order.ECommercePlatForm();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.ECommerceCompany }
     * 
     */
    public CBEC.Declaration.Order.ECommerceCompany createCBECDeclarationOrderECommerceCompany() {
        return new CBEC.Declaration.Order.ECommerceCompany();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.TotalAmount }
     * 
     */
    public CBEC.Declaration.Order.TotalAmount createCBECDeclarationOrderTotalAmount() {
        return new CBEC.Declaration.Order.TotalAmount();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.Freight }
     * 
     */
    public CBEC.Declaration.Order.Freight createCBECDeclarationOrderFreight() {
        return new CBEC.Declaration.Order.Freight();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.TaxAmount }
     * 
     */
    public CBEC.Declaration.Order.TaxAmount createCBECDeclarationOrderTaxAmount() {
        return new CBEC.Declaration.Order.TaxAmount();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.ActualAmountPaid }
     * 
     */
    public CBEC.Declaration.Order.ActualAmountPaid createCBECDeclarationOrderActualAmountPaid() {
        return new CBEC.Declaration.Order.ActualAmountPaid();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.OtherCharges }
     * 
     */
    public CBEC.Declaration.Order.OtherCharges createCBECDeclarationOrderOtherCharges() {
        return new CBEC.Declaration.Order.OtherCharges();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.Item }
     * 
     */
    public CBEC.Declaration.Order.Item createCBECDeclarationOrderItem() {
        return new CBEC.Declaration.Order.Item();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.Payment.PaymentCompany }
     * 
     */
    public CBEC.Declaration.Order.Payment.PaymentCompany createCBECDeclarationOrderPaymentPaymentCompany() {
        return new CBEC.Declaration.Order.Payment.PaymentCompany();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.OtherPayment.Amount }
     * 
     */
    public CBEC.Declaration.Order.OtherPayment.Amount createCBECDeclarationOrderOtherPaymentAmount() {
        return new CBEC.Declaration.Order.OtherPayment.Amount();
    }

    /**
     * Create an instance of {@link CBEC.Declaration.Order.Buyer.IDNumber }
     * 
     */
    public CBEC.Declaration.Order.Buyer.IDNumber createCBECDeclarationOrderBuyerIDNumber() {
        return new CBEC.Declaration.Order.Buyer.IDNumber();
    }

}
