//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 03:45:49 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:gacc:datamodel:GZ:CBEC103:1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ecms.customs.vo.cust1;
